---
#==== all.yml
admin_token: 1231412342341234wqwe

### MySQL DB info
mysql_login_user: root
mysql_login_password: ''

## MySQL Databases for each service ##
mysql_keystone_db: keystonedb
mysql_keystone_user: keystone
mysql_keystone_password: keystonepass

mysql_glance_db: glancedb
mysql_glance_user: glance
mysql_glance_password: glancepass

mysql_neutron_db: neutrondb
mysql_neutron_user: neutron
mysql_neutron_password: neutronpass

mysql_nova_db: novadb
mysql_nova_user: nova
mysql_nova_password: novapass

## OpenStack bootstrap user/role/tenant config
keystone_admin_username: admin
keystone_admin_password: adminXX
keystone_admin_email: admin@example.com
keystone_admin_tenant: admin

# do not change below setting, otherwise you'll have 
# you'll have to overhaul security policies as well
keystone_admin_role: admin

service_tenant: Services

keystone_force_init: True
glance_force_init: True
neutron_force_init: True
nova_force_init: True

virtual_deploy: True
rdo_vif_workaround: True

#==== cinder.yml

cinder_service_user: cinder
cinder_service_user_password: cinderpw
cinder_service_user_email: cinder@example.com
cinder_service_mysql_user: cinder
cinder_service_mysql_user_password: cinderpw

cinder_service_region: RegionOne
cinder_service_admin_ip: "{{ ansible_default_ipv4.address }}"
cinder_service_public_ip: "{{ ansible_default_ipv4.address }}"
cinder_service_internal_ip: "{{ ansible_default_ipv4.address }}"

#==== glance.yml

glance_service_user: glance
glance_service_user_password: glancepw
glance_service_user_email: glance@example.com
glance_service_mysql_user: glance
glance_service_mysql_user_password: glancepw

glance_service_region: RegionOne
glance_service_admin_ip: "{{ ansible_default_ipv4.address }}"
glance_service_public_ip: "{{ ansible_default_ipv4.address }}"
glance_service_internal_ip: "{{ ansible_default_ipv4.address }}"

#==== keystone.yml

keystone_service_user: keystone
keystone_service_user_password: keystonepw
keystone_service_user_email: keystone@example.com
keystone_service_mysql_user: keystone
keystone_service_mysql_user_password: keystonepw

keystone_service_region: RegionOne
keystone_service_admin_ip: "{{ ansible_default_ipv4.address }}"
keystone_service_public_ip: "{{ ansible_default_ipv4.address }}"
keystone_service_internal_ip: "{{ ansible_default_ipv4.address }}"

#==== neutron.yml

neutron_service_user: neutron
neutron_service_user_password: neutronpw
neutron_service_user_email: neutron@example.com
neutron_service_mysql_user: neutron
neutron_service_mysql_user_password: neutronpw

neutron_service_region: RegionOne
neutron_service_admin_ip: "{{ ansible_default_ipv4.address }}"
neutron_service_public_ip: "{{ ansible_default_ipv4.address }}"
neutron_service_internal_ip: "{{ ansible_default_ipv4.address }}"

neutron_metadata_proxy_shared_secret: abracadabrasimsalabim
instance_tunnels_interface_ip: 10.0.1.21
phys_net_interface: eth0

#==== nova.yml

nova_service_user: nova
nova_service_user_password: novapw
nova_service_user_email: nova@example.com
nova_service_mysql_user: nova
nova_service_mysql_user_password: novapw

nova_service_region: RegionOne
nova_service_admin_ip: "{{ ansible_default_ipv4.address }}"
nova_service_public_ip: "{{ ansible_default_ipv4.address }}"
nova_service_internal_ip: "{{ ansible_default_ipv4.address }}"

