---

admin_token: 1231412342341234wqwe

### MySQL DB info
mysql_login_user: root
mysql_login_password: ''

## MySQL Databases for each service ##
mysql_keystone_db: keystonedb
mysql_keystone_user: keystone
mysql_keystone_password: keystonepass

mysql_glance_db: glancedb
mysql_glance_user: glance
mysql_glance_password: glancepass

mysql_neutron_db: neutrondb
mysql_neutron_user: neutron
mysql_neutron_password: neutronpass

mysql_nova_db: novadb
mysql_nova_user: nova
mysql_nova_password: novapass

mysql_cinder_db: cinderdb
mysql_cinder_user: cinder
mysql_cinder_password: cinderpass

## OpenStack buutstrap user/role/tenant config
keystone_admin_username: admin
keystone_admin_password: adminXX
keystone_admin_email: admin@example.com
keystone_admin_tenant: MyFirstProject

# do NOT change below setting, otherwise
# you'll have to overhaul security policies as well
keystone_admin_role: admin

service_tenant: Services

keystone_force_init: True
glance_force_init: True
neutron_force_init: True
nova_force_init: True
horizon_force_init: True
cinder_force_init: True

virtual_deploy: True
rdo_vif_workaround: True
