---

glance_service_user: glance
glance_service_user_password: glancepw
glance_service_user_email: glance@example.com
glance_service_mysql_user: glance
glance_service_mysql_user_password: glancepw

## set specifics here if you don't like
## default values set for _all_ hosts
# service_region: RegionOne
# service_admin_ip: localhost
# service_public_ip: localhost
# service_internal_ip: localhost

glance_service_region: RegionOne
glance_service_admin_ip: "{{ ansible_default_ipv4.address }}"
glance_service_public_ip: "{{ ansible_default_ipv4.address }}"
glance_service_internal_ip: "{{ ansible_default_ipv4.address }}"

