---

nova_service_user: nova
nova_service_user_password: nova
nova_service_user_email: nova@example.com
nova_service_mysql_user: nova
nova_service_mysql_user_password: nova

## set specifics here if you don't like
## default values set for _all_ hosts
# service_region: RegionOne
# service_admin_ip: localhost
# service_public_ip: localhost
# service_internal_ip: localhost

nova_service_region: RegionOne
nova_service_admin_ip: "{{ ansible_default_ipv4.address }}"
nova_service_public_ip: "{{ ansible_default_ipv4.address }}"
nova_service_internal_ip: "{{ ansible_default_ipv4.address }}"

