---

- name: install qpid
  yum: name=qpid-cpp-server state=present
  tags: [ 'install' ]

- name: open up external access to qpidd
  shell: lokkit --port 5672:tcp
  tags: [ 'configure' ]

- name: enable qpid server
  service: name=qpidd state=started enabled=yes
  tags: [ 'configure' ]
