---

- hosts: all
  vars_prompt:
  - name: my_config
    default: "sample_config"
    prompt: "Which config file you'd like to use?"
    private: no
  vars_files: 
  - "{{ my_config }}.yml"
- hosts: keystone
  vars_files: 
  - "{{ my_config }}.yml"
  vars:
     # auth_url: "http://{{ groups['keystone'][0] }}:5000/v2.0/"
     # tenant: "{{ sample_tenant }}"
     # region: "{{ sample_region }}"

  tasks:
  - keystone_user: tenant="{{ tenant }}"
                     tenant_description="{{ tenant }}"
                     login_user="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
                     state=present
    register: project_tenant
  - keystone_user: tenant="{{ keystone_admin_tenant }}"
                     tenant_description="{{ tenant }}"
                     login_user="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
                     state=present
    register: admin_tenant

- hosts: neutron-controller
  vars_files: 
  - "{{ my_config }}.yml"
  tasks:
  - name: create private net
    quantum_network: name=private 
                     state=present
                     tenant_name="{{ tenant }}"
                     auth_url="{{ auth_url }}"
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: priv_net
  - name: create private subnet
    quantum_subnet: name=private-subnet1 
                     network_name=private 
                     cidr={{ sample_priv_net_cidr }}
                     state=present
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: priv_subnet
  - name: create public net
    quantum_network: name=public 
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
                     router_external=yes 
                     shared=yes
    register: pub_net
  - name: create public subnet
    quantum_subnet: name=public-subnet1 
                     network_name=public 
                     cidr={{ sample_pub_net_cidr }}
                     allocation_pool_start={{ sample_pub_net_start }}
                     allocation_pool_end={{ sample_pub_net_end }}
                     enable_dhcp=no
                     state=present
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: pub_subnet

- hosts: glance
  vars_files: 
  - "{{ my_config }}.yml"
  tasks:
  - name: add image to glance
    glance_image: login_username="{{ keystone_admin_username }}"
                  login_password="{{ keystone_admin_password }}"
                  login_tenant_name="{{ keystone_admin_tenant }}"
                  region_name="{{ region }}"
                  auth_url="{{ auth_url }}"
                  name={{ sample_image_name }}
                  container_format=bare
                  disk_format=qcow2
                  state=present
                  file={{ sample_image_file }}
    register: sample_img

- hosts: nova-controller
  vars_files: 
  - "{{ my_config }}.yml"
  tasks:
  - nova_compute:
         state: present
         login_username: "{{ keystone_admin_username }}"
         login_password: "{{ keystone_admin_password }}"
         login_tenant_name: "{{ keystone_admin_tenant }}"
         name: "{{ sample_instance_name }}"
         image_id: "{{ sample_img.id }}"
         wait_for: 200
         flavor_id: 1
         nics: 
         - net-id: "{{ priv_net.id }}"
    register: myfirstinstance

  - script: files/nova-secgroup.sh
    ignore_errors: True


- hosts: neutron-controller
  vars_files: 
  - "{{ my_config }}.yml"
  tasks:

  - name: create router
    quantum_router: name=real_router 
                     state=present
                     tenant_name="{{ tenant }}"
                     auth_url="{{ auth_url }}"
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: real_router
  - name: add interface to a router
    quantum_router_interface: 
                     router_name=real_router
                     subnet_name=private-subnet1
                     state=present
                     tenant_name="{{ tenant }}"
                     auth_url="{{ auth_url }}"
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: router_priv_net
  - name: add gateway interface to a router
    quantum_router_gateway: 
                     router_name=real_router
                     network_name=public
                     state=present
                     auth_url="{{ auth_url }}"
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"
    register: router_priv_net
  - name: add floating IP
    quantum_floating_ip: 
                     network_name=public
                     internal_network_name=private
                     instance_name={{ sample_instance_name }}
                     state=present
                     auth_url="{{ auth_url }}"
                     login_username="{{ keystone_admin_username }}"
                     login_password="{{ keystone_admin_password }}"
                     login_tenant_name="{{ keystone_admin_tenant }}"

### Missing statements:
#  nova secgroup-add-rule default tcp 22 22 0.0.0.0/0
#  nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0



##   - name: add floating IP
##     quantum_floating_ip_associate: 
##                      ip_address=192.168.0.240
##                      instance_name=MyFirstInstance
##                      state=present
##                      auth_url="{{ auth_url }}"
##                      login_username="{{ keystone_admin_username }}"
##                      login_password="{{ keystone_admin_password }}"
##                      login_tenant_name="{{ keystone_admin_tenant }}"
