---

auth_url: "http://{{ groups['keystone'][0] }}:5000/v2.0/"
tenant: MyFirstProject
region: RegionOne
sample_priv_net_cidr: 10.0.0.0/24
#!!! Has to match your CIDR for real net configured on br-ex
sample_pub_net_cidr: 192.168.0.0/24
# you'll have to first drop off image into that location:
sample_image_file: "/tmp/images/cirros-0.3.2-x86_64-disk.img"
sample_image_name: 'cirros'
sample_instance_name: MyFirstInstance
sample_flavor_id: 1
sample_pub_net_start: 192.168.0.128
sample_pub_net_end: 192.168.0.140
sample_pub_net_gw: 192.168.0.1
sample_pub_dns: 192.168.0.1
sample_priv_dns: "{{ sample_pub_dns }}"
# If you want specific IP associated from existing "floaters":
# sample_pub_net_ip: 192.168.0.1
