---

############################
### workaround for Jinja bug
### https://github.com/ansible/ansible/issues/7799
- hosts: keystone
  tasks:
    - set_fact: keystone_service_admin_ip={{ keystone_service_admin_ip }}
    - set_fact: keystone_service_public_ip={{ keystone_service_public_ip }}
    - set_fact: keystone_service_internal_ip={{ keystone_service_internal_ip }}

- hosts: glance
  tasks:
    - set_fact: glance_service_admin_ip={{ glance_service_admin_ip }}
    - set_fact: glance_service_public_ip={{ glance_service_public_ip }}
    - set_fact: glance_service_internal_ip={{ glance_service_internal_ip }}

- hosts: nova
  tasks:
    - set_fact: nova_service_admin_ip={{ nova_service_admin_ip }}
    - set_fact: nova_service_public_ip={{ nova_service_public_ip }}
    - set_fact: nova_service_internal_ip={{ nova_service_internal_ip }}

- hosts: cinder
  tasks:
    - set_fact: cinder_service_admin_ip={{ cinder_service_admin_ip }}
    - set_fact: cinder_service_public_ip={{ cinder_service_public_ip }}
    - set_fact: cinder_service_internal_ip={{ cinder_service_internal_ip }}

- hosts: neutron
  tasks:
    - set_fact: neutron_service_admin_ip={{ neutron_service_admin_ip }}
    - set_fact: neutron_service_public_ip={{ neutron_service_public_ip }}
    - set_fact: neutron_service_internal_ip={{ neutron_service_internal_ip }}

###
### end of workaround
############################

- hosts: all
  roles:
  - role: common

- hosts: mysql
  roles:
  - role: mysql


- hosts: qpid
  roles:
  - role: qpid


- hosts: keystone
  roles:
  - role: openstack-common
  - role: keystone

- hosts: glance
  roles:
  - role: openstack-common
  - role: glance

- hosts: neutron-controller
  roles:
  - role: openstack-common
  - role: neutron-controller

- hosts: neutron-network
  roles:
  - role: openstack-common
  - role: neutron-network

- hosts: nova-controller
  roles:
  - role: openstack-common
  - role: nova-controller

- hosts: nova-compute
  roles:
  - role: openstack-common
  - role: nova-compute

- hosts: horizon
  roles:
  - role: openstack-common
  - role: horizon

## Not done yet:

- hosts: cinder-controller
  roles:
  - role: openstack-common
  - role: cinder-controller

- hosts: cinder-node
  roles:
  - role: openstack-common
  - role: cinder-node

### - hosts: swift
###   roles:
###   - role: openstack-common
###   - role: swift

- hosts: heat
  roles:
  - role: openstack-common
  - role: heat

# This will need to be split into sub-sections for each service
- hosts: ceilometer
  roles:
  - role: openstack-common
  - role: ceilometer

- hosts: trove
  roles:
  - role: openstack-common
  - role: trove

