---

- include: common.yml

- hosts: mysql
  roles:
  - role: mysql

- hosts: qpid
  roles:
  - role: qpid

- hosts: keystone
  roles:
  - role: openstack-common
  - role: keystone

- hosts: glance
  roles:
  - role: openstack-common
  - role: glance

- hosts: neutron-controller
  roles:
  - role: openstack-common
  - role: neutron-controller

- hosts: neutron-network
  roles:
  - role: openstack-common
  - role: neutron-network

- hosts: nova-controller
  roles:
  - role: openstack-common
  - role: nova-controller

- hosts: nova-compute
  roles:
  - role: openstack-common
  - role: nova-compute

- hosts: horizon
  roles:
  - role: openstack-common
  - role: horizon

- hosts: cinder-controller
  roles:
  - role: openstack-common
  - role: cinder-controller

- hosts: cinder-node
  roles:
  - role: openstack-common
  - role: cinder-node

## Not done yet:

##TODO #### Will need to be split up into sub-sections as there are multiple
##TODO #### components involved
##TODO ### - hosts: swift
##TODO ###   roles:
##TODO ###   - role: openstack-common
##TODO ###   - role: swift
##TODO 
##TODO - hosts: heat
##TODO   roles:
##TODO   - role: openstack-common
##TODO   - role: heat
##TODO 
##TODO #### This will need to be split into sub-sections for each service
##TODO ### - hosts: ceilometer
##TODO ###   roles:
##TODO ###   - role: openstack-common
##TODO ###   - role: ceilometer
##TODO 
##TODO - hosts: trove
##TODO   roles:
##TODO   - role: openstack-common
##TODO   - role: trove
##TODO 
