---

- name: install neutron and dependencies
  yum: name={{ item }} state=present
  with_items:
  - openstack-neutron
  - openstack-neutron-openvswitch
  - openstack-neutron-ml2
  tags:
  - install


- name: configure firewall
  shell: lokkit --port {{ item }}:tcp
  with_items:
  - 9696
  tags:
  - configure


- name: stop neutron services
  service: name=neutron-server state=stopped
  when: neutron_force_init == True
  tags:
  - service_stop

- name: drop neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=absent login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}
  when: neutron_force_init == True
  tags:
  - initialize

  
- name: create neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=present login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}
  tags:
  - initialize


- name: create neutron user
  mysql_user: name={{ mysql_neutron_user }} state=present host='{{ item }}' password="{{ mysql_neutron_password }}" priv={{ mysql_neutron_db }}.*:ALL login_user=root login_password=''
  with_items: groups['neutron-controller']
  tags:
  - initialize


- name: configure Neutron & OpenVSwitch plugin
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - { 'src': 'neutron.conf.j2', 'dest':'/etc/neutron/neutron.conf' }
  - { 'src': 'ml2_conf.ini.j2', 'dest': '/etc/neutron/plugins/ml2/ml2_conf.ini' }
  # - { 'src': 'ovs_neutron_plugin.ini.j2', 'dest': '/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini' }
  tags:
  - configure


- name: make sure plugin.ini is there
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link force=yes
  tags:
  - configure

- name: make sure ovs_neutron_plugin.ini is pointing to plugin.init
  file: dest=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini src=/etc/neutron/plugin.ini state=link force=yes
  tags:
  - configure


- name: start neutron services
  service: name=neutron-server state=started enabled=yes
  tags:
  - service_start

###FIXME
# restart compute after this as per:
# http://docs.openstack.org/icehouse/install-guide/install/yum/content/neutron-ml2-controller-node.html
  
