---

- name: install RDO repo
  yum: name=http://rdo.fedorapeople.org/rdo-release.rpm state=present

- name: install openstack-utils
  yum: name=openstack-utils state=present

- name: install SELinux bindings
  yum: name=libselinux-python state=present
