---

## quite possibly an overkill for subscriptions here...
- name: subscibe to all the proper channels via subscription manager
  ## no module for subscription-manager's repo subcommand
  shell: creates=/var/cache/yum/x86_64/6Server/{{ item }} subscription-manager repos --enable={{ item }}
  ## rhn_challe is kind of obsolete
  # rhn_channel: name={{ item }} sysname={{ inventory_hostname }} url=https://rhn.redhat.com/rpc/api user={{ rhn_user }} password={{ rhn_password }}
  with_items:
  - rhel-6-server-supplementary-rpms
  - rhel-6-server-rh-common-rpms
  - rhel-server-rhscl-6-rpms
  - rhel-6-server-rhn-tools-rpms
  - rhel-6-server-rpms
  - rhel-server-rhscl-6-eus-rpms
  - rhel-6-server-extras-rpms
  - rhel-6-server-optional-rpms
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 6
  tags:
  - install

- name: install yum-plugin-priorities
  yum: name=yum-plugin-priorities state=present
  tags:
  - install

## Bootstrap EPEL, as per
# https://www.zigg.com/2013/yum-repository-bootstrapping-ansible.html

- name: bootstrap epel-release install
  copy: src=ansible-bootstrap-epel.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644
  tags:
  - install
  - repo_setup


- name: epel-release install
  yum: name=epel-release
       enablerepo=ansible-bootstrap-epel
       state=present
  tags:
  - install
  - repo_setup


- name: epel repository enable
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section=epel
            option=enabled
            value=1
  tags:
  - install
  - repo_setup


- name: install RDO repo
  # yum: name=http://rdo.fedorapeople.org/rdo-release.rpm state=present
  # yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-icehouse/rdo-release-icehouse-4.noarch.rpm state=present
  yum: name={{ rdo_rpm_url }} state=present
  tags:
  - install
  - repo_setup


- name: install openstack-utils
  yum: name=openstack-utils state=present
  tags:
  - install


- name: install openstack-selinux
  yum: name=openstack-selinux state=present
  when: use_selinux is defined and use_selinux == True
  tags:
  - install


##MOVED - name: install SELinux bindings
  ##MOVED yum: name=libselinux-python state=present

- name: install RDO-compatible iproute
  yum: name=iproute state=latest
  tags:
  - install

- name: Yum distribution-synchronization
  shell: yum -y distribution-synchronization
  tags:
  - install
  - update


