
## Neutron-config
- name: modify sysctl
  sysctl: name={{ item.name }} value={{ item.value }} state=present
  with_items:
  - { 'name':'net.ipv4.conf.all.rp_filter', 'value':'0' }
  - { 'name':'net.ipv4.conf.default.rp_filter', 'value':'0' }

- name: install network packages
  yum: name={{ item }} state=present
  with_items:
  - openstack-neutron-ml2
  - openstack-neutron-openvswitch

- name: configure Neutron & OpenVSwitch plugin
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - { 'src': 'neutron.conf.j2', 'dest':'/etc/neutron/neutron.conf' }
  - { 'src': 'ml2_conf.ini.j2', 'dest': '/etc/neutron/plugins/ml2/ml2_conf.ini' }

- name: start openvswitch
  service: name=openvswitch state=started enabled=yes

- name: create integration bridge
  openvswitch_bridge: bridge=br-int state=present

- name: make sure plugin.ini is there
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link force=yes

- name: restart compute service
  service: name=openstack-nova-compute state=restarted enabled=yes

- name: start openvswitch-agent
  service: name=neutron-openvswitch-agent state=restarted enabled=yes

