---

- name: install compute services
  yum: name=openstack-nova-compute

- name: stop services
  service: name=openstack-nova-compute state=stopped
  when: nova_force_init == True
  tags:
  - service_stop

- name: configure nova compute
  template: src=roles/nova-controller/templates/unified-nova.conf.j2 dest=/etc/nova/nova.conf backup=yes
  notify: restart nova-compute
  tags:
  - configure


- name: startup services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - libvirtd
  - messagebus
  - openstack-nova-compute
  tags:
  - service_start

## Neutron-config
- name: modify sysctl
  sysctl: name={{ item.name }} value={{ item.value }} state=present
  with_items:
  - { 'name':'net.ipv4.conf.all.rp_filter', 'value':'0' }
  - { 'name':'net.ipv4.conf.default.rp_filter', 'value':'0' }
  tags:
  - configure


- name: install network packages
  yum: name={{ item }} state=present
  with_items:
  - openstack-neutron-ml2
  - openstack-neutron-openvswitch

- name: configure Neutron & OpenVSwitch plugin
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - { 'src': 'roles/neutron-controller/templates/neutron.conf.j2', 'dest':'/etc/neutron/neutron.conf' }
  - { 'src': 'roles/neutron-controller/templates/ml2_conf.ini.j2', 'dest': '/etc/neutron/plugins/ml2/ml2_conf.ini' }
  tags:
  - configure


- name: start openvswitch
  service: name=openvswitch state=started enabled=yes
  tags:
  - service_start

- name: create integration bridge
  openvswitch_bridge: bridge=br-int state=present
  tags:
  - initialize


- name: make sure plugin.ini is there
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link force=yes
  tags:
  - configure


- name: restart compute service
  service: name=openstack-nova-compute state=restarted enabled=yes
  tags:
  - service_start
  - service_restart

- name: start openvswitch-agent
  service: name=neutron-openvswitch-agent state=restarted enabled=yes
  tags:
  - service_start
  - service_restart

