---

- name: install neutron and dependencies
  yum: name={{ item }} state=present
  with_items:
  - openstack-neutron
  - openstack-neutron-vswitch


- name: stop neutron
  service: name=openstack-{{ item }} state=stopped
  when: neutron_force_init == True
  with_items:
  - neutron

- name: drop neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=absent login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}
  when: glance_force_init == True
  
- name: create neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=present login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}

- name: create neutron user
  mysql_user: name={{ mysql_neutron_user }} state=present host='{{ item }}' password="{{ mysql_neutron_password }}" priv={{ mysql_glance_db }}.*:ALL login_user=root login_password=''
  with_items: groups['neutron']

