---
# Loosely based on:
# http://docs.openstack.org/icehouse/install-guide/install/yum/content/neutron-ml2-controller-node.html
#
- name: install neutron and dependencies
  yum: name={{ item }} state=present
  with_items:
  - openstack-neutron
  - openstack-neutron-openvswitch
  - openstack-neutron-ml2

- name: stop neutron & openvswitch
  service: name={{ item }} state=stopped
  when: neutron_force_init == True
  with_items:
  - neutron-server
  - neutron-openvswitch-agent
  - neutron-dhcp-agent
  - neutron-l3-agent
  - openvswitch

- name: drop neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=absent login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}
  when: neutron_force_init == True
  
- name: create neutron DB
  mysql_db: name={{ mysql_neutron_db }} state=present login_user={{ mysql_login_user }}  login_password={{ mysql_login_password }}

- name: create neutron user
  mysql_user: name={{ mysql_neutron_user }} state=present host='{{ item }}' password="{{ mysql_neutron_password }}" priv={{ mysql_glance_db }}.*:ALL login_user=root login_password=''
  with_items: groups['neutron']

- name: configure NEutron & OpenVSwitch plugin
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - { 'src': 'neutron.conf.j2', 'dest':'/etc/neutron/neutron.conf' }
  - { 'src': 'ovs_neutron_plugin.ini.j2', 'dest':'/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini' }
  - { 'src': 'l3_agent.ini.j2', 'dest':'/etc/neutron/l3_agent.ini' }
  - { 'src': 'dhcp_agent.ini.j2', 'dest':'/etc/neutron/dhcp_agent.ini' }
  - { 'src': 'ml2_conf.ini.j2', 'dest': '/etc/neutron/plugins/ml2/ml2_conf.ini' }

- name: make sure plugin.ini is there
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini state=link force=yes

- name: start OpenVSwitch
  service: name=openvswitch state=started enabled=yes

# referenced in /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
- name: create integration bridge
  openvswitch_bridge: bridge=br-int state=present

# referenced in /etc/neutron/l3_agent.ini
- name: create external bridge
  openvswitch_bridge: bridge=br-ex state=present

- name: start neutron 
  service: name={{ item }} state=started enabled=yes
  with_items:
  - neutron-server
  - neutron-openvswitch-agent
  - neutron-dhcp-agent
  - neutron-l3-agent


# network node

- name: modify sysctl
  sysctl: name={{ item.name }} value={{ item.value }} state=present
  with_items:
  - { 'name':'net.ipv4.ip_forward', 'value':'1' }
  - { 'name':'net.ipv4.conf.all.rp_filter', 'value':'0' }
  - { 'name':'net.ipv4.conf.default.rp_filter', 'value':'0' }

##FIXME
- name: add OVS port
  openvswitch_port: bridge=br-ex port={{ phys_net_interface }} state=present

