---

### actually needed on nodes and there it's covered by openstack-* 
### dependencies
## - name: install python-MySQL
##   yum: name=MySQL-python state=present
 
- name: install mysql server
  yum: name=mysql-server state=present

##MOVED - name: change default bind IP
##MOVED   ini_file: dest=/etc/my.cnf
##MOVED             section=mysqld
##MOVED             option=bind-address
##MOVED             value="0.0.0.0"
##MOVED             state=present
##MOVED   notify: restart mysqld
##MOVED 
##MOVED - name: configure UTF8
##MOVED   ini_file: dest=/etc/my.cnf
##MOVED             section=mysqld
##MOVED             option={{ item.key }}
##MOVED             value={{ item.value }}
##MOVED             state=present
##MOVED   with_items:
##MOVED   - { 'key':'collation-server',  'value':'utf8_general_ci' }
##MOVED   - { 'key':'init-connect', 'value':'SET NAMES utf8' }
##MOVED   - { 'key':'character-set-server', 'value':'utf8' }
##MOVED   notify: restart mysqld
##MOVED 

- name: configure MySQLd
  copy: src=my.cnf dest=/etc/my.cnf
  notify: restart mysqld

- name: Enable and startup service
  service: name=mysqld enabled=yes

#### Maybe better to do it from each node?
### - name: Add nodes to MySQL allowed list
###   shell: echo "{{ item }}" >> /tmp/log
###   with_items: ( groups['keystone']+groups['qpid'] ) | unique

- name: open up external access to MySQL
  shell: lokkit --port 3306:tcp
