---

- name: install cinder-node packages
  yum: name={{ item }} state=present
  with_items:
  - openstack-cinder
  - scsi-target-utils
  tags:
  - install


- name: open up external access to iSCSI
  shell: lokkit --port 3260:tcp
  tags:
  - configure

- name: stop cinder-node services
  service: name={{ item }} state=stopped
  when: cinder_force_init == True
  with_items:
  - openstack-cinder-volume
  - tgtd
  tags:
  - service_stop

- name: configure cinder-node
  template: src=roles/cinder-controller/templates/cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  tags:
  - configure

- name: configure tgt
  copy: src={{ item.src }} dest={{ item.dest }} backup=yes
  tags: 
  - configure
  with_items:
  - { 'src': 'tgt_targets.conf', 'dest': '/etc/tgt/targets.conf' }
  - { 'src': 'tgt_cinder.conf',  'dest': '/etc/tgt/conf.d/cinder.conf' }
  notify:
  - restart tgtd

- name: startup and enable cinder-node services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - openstack-cinder-volume
  - tgtd
  tags:
  - service_start
