---

- name: install cinder-node packages
  yum: name={{ item }} state=present
  with_items:
  - openstack-cinder
  - scsi-target-utils
  tags:
  - install


- name: open up external access to iSCSI
  shell: lokkit --port 3260:tcp
  tags:
  - configure

- name: stop cinder-node services
  service: name={{ item }} state=stopped
  when: cinder_force_init == True
  with_items:
  - openstack-cinder-volume
  - tgtd
  tags:
  - service_stop

- name: configure cinder-node
  template: src=roles/cinder-controller/templates/cinder.conf.j2 dest=/etc/cinder/cinder.conf backup=yes
  tags:
  - configure

- name: tune sysctl params for iSCSI
  sysctl: name="{{ item.key }}" value="{{ item.value }}" sysctl_set=yes state=present reload=yes
  with_items:
    - { key: net.core.rmem_max, value: 8388608 }
    - { key: net.core.wmem_max, value: 8388608 }
    - { key: net.core.rmem_default, value: 65536 }
    - { key: net.core.wmem_default, value: 65536 }
    - { key: net.ipv4.tcp_rmem , value: "4096 87380 8388608" }
    - { key: net.ipv4.tcp_wmem , value: "4096 65536 8388608" }
    - { key: net.ipv4.tcp_mem , value: "8388608 8388608 8388608" }
    - { key: net.ipv4.route.flush , value: 1 }
  tags:
  - configure

- name: configure tgt
  copy: src={{ item.src }} dest={{ item.dest }} backup=yes
  tags: 
  - configure
  with_items:
  - { 'src': 'tgt_targets.conf', 'dest': '/etc/tgt/targets.conf' }
  - { 'src': 'tgt_cinder.conf',  'dest': '/etc/tgt/conf.d/cinder.conf' }
  notify:
  - restart tgtd

- name: startup and enable cinder-node services
  service: name={{ item }} state=started enabled=yes
  with_items:
  - openstack-cinder-volume
  - tgtd
  tags:
  - service_start
